### PR TITLE
Add svelte, astro and vue to supported languages

### PR DESCRIPTION
**Pull request by mattpocock**

### CODE REVIEW

**Comment by Princesseuh** [comment]
Hello, Erika from the Astro team here! 😄 

I absolutely love this extension and would love to see Astro support for it. Let me know if there's anything we can do to help!

It seems like this extension uses a VS Code command from the TypeScript's extension - we could definitely expose something similar

**Comment by orta** [comment]
I think you could pretty trivially build this into the astro extension - then everyone gets the feature! This extension talks to the vscode provided TypeScript server for JS projects (which is why it's 75LOC) via https://github.com/microsoft/vscode/pull/138279

The LSPs for Astro / Vue / Svelte all have their _own_ TypeScript server instead of using the default one in vscode (because it doesn't understand `.astro` files for example)

**Comment by vaaski** [comment]
Is there any update on this? I would love to see this happen

**Comment by orta** [comment]
Nope, I should close this as it's not a possible route for someone to add support as I mentioned above

**Pull request closed without merging**
